language: node_js
node_js: 
  -16.12.0
cache: npm
before_install: 
install:
  -npm install
script: 
  -npm test
  -npm run build
deploy: 
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
after_deploy:
